In [3]:
import pandas as pd

### Guide to understanding the content of this notebook

- Reviewing the datasets found.
- Discarded two.
- Picked the Annual Household Income and Expenditure Survey  (AHIES)
  <br> dataset and Ministry of Food and Agriculture (MoFA) Agricultural Commodity Prices for 2025 dataset to further explore.

  <br>
  <br>

  #### MoFA dataset
##### Procedures performed on MoFA dataset.

- Filtered commodities to be considered since most of the interviewees worked with these commodities.
- Dropped geolocation column.

##### Challenges and limitations faced with the MoFA dataset.
- Dataset is only from the year 2025.
- There is no further description of the price whether it is price per kg.

#### AHIES dataset
##### Procedures performed on AHIES dataset.
- Deciphered the meaning of the columns.
- Filtered occupation column values to farmer.
- Further filtered occupations that support the farmer like farm labourer and worker.

##### Challenges and limitations faced with the AHIES dataset
- Some challenges faced for AHIES are the lack proper documentation of what the columns mean.
- Most of the columns are invented codes, hence no proper definitions.
- Columns presented in the chosen dataset were maually deciphered.

### Examining datasets

In [8]:
data = pd.read_csv(r"C:\Users\rauda\Downloads\national_cropped _area_2019_to_2023.csv") # Total commodities produced dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   COMMODITY  14 non-null     object
 1   2019       14 non-null     object
 2   2020       14 non-null     object
 3   2021       14 non-null     object
 4   2022       14 non-null     object
 5   2023       14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes

In [11]:
data.head()

   COMMODITY         2019         2020         2021         2022         2023
0    Cassava   1,021,251    1,013,190    1,051,455    1,079,136    1,141,359
1    Cocoyam     214,088      216,444      218,753      221,849      231,197
2     Cowpea     169,480      172,506      179,763      191,174      199,299
3  Groundnut     336,851      262,287      272,635      297,223      314,162
4      Maize   1,150,280    1,182,710    1,266,435    1,251,726    1,339,407

No engaging insights were derived from this dataset hence no analysis was performed

#### Data from the faostat.

In [4]:
data_faostat = pd.read_csv(r"C:\Users\rauda\Downloads\FAOSTAT_data_en_8-7-2026.csv")

In [5]:
data_faostat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       81 non-null     object
 1   Domain            81 non-null     object
 2   Area Code (M49)   81 non-null     int64
 3   Area              81 non-null     object
 4   Element Code      81 non-null     int64
 5   Element           81 non-null     object
 6   Item Code (CPC)   81 non-null     int64
 7   Item              81 non-null     object
 8   Year Code         81 non-null     int64
 9   Year              81 non-null     int64
 10  Unit              81 non-null     object
 11  Value             81 non-null     float64
 12  Flag              81 non-null     object
 13  Flag Description  81 non-null     object
 14  Note              19 non-null     object
dtypes: float64(1), int64(5), object(9)
memory usage: 9.6+ KB

In [7]:
data_faostat.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,288,Ghana,5312,Area harvested,1652,"Chillies and peppers, dry (Capsicum spp., Pime...",2022,2022,ha,14834.00,I,Value imputed by a receiving agency,NaN
1,QCL,Crops and livestock products,288,Ghana,5412,Yield,1652,"Chillies and peppers, dry (Capsicum spp., Pime...",2022,2022,kg/ha,7473.80,E,Estimated value,NaN
2,QCL,Crops and livestock products,288,Ghana,5510,Production,1652,"Chillies and peppers, dry (Capsicum spp., Pime...",2022,2022,t,110863.82,E,Estimated value,NaN
3,QCL,Crops and livestock products,288,Ghana,5312,Area harvested,1652,"Chillies and peppers, dry (Capsicum spp., Pime...",2023,2023,ha,14890.00,I,Value imputed by a receiving agency,NaN
4,QCL,Crops and livestock products,288,Ghana,5412,Yield,1652,"Chillies and peppers, dry (Capsicum spp., Pime...",2023,2023,kg/ha,7457.70,E,Estimated value,NaN

In [8]:
data_faostat["Note"].value_counts() #Checking for missing values

Note
Unofficial figure    19
Name: count, dtype: int64

In [9]:
data_faostat = data_faostat.drop(columns=['Note']) # Dropping the column since majority are missing values

In [ ]:
data_faostat.to_csv('faostat.csv',index=False)

No engaging insights were derived from this dataset hence no analysis was performed.

### Agricultural commodity prices from MOFA

In [4]:
data_mofa_acp = pd.read_csv(r"C:\Users\rauda\Downloads\Commodity prices _041125.csv")
data_mofa_acp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10779 entries, 0 to 10778
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        10779 non-null  object
 1   district      10779 non-null  object
 2   date          10779 non-null  object
 3   Market        10345 non-null  object
 4   source        10779 non-null  object
 5   _geolocation  0 non-null      float64
 6   commodity     10779 non-null  object
 7   Price         10779 non-null  float64
 8   market_day    10779 non-null  object
 9   Year          10779 non-null  int64
 10  month         10779 non-null  int64
 11  week          10779 non-null  int64
 12  Type          10779 non-null  object
dtypes: float64(2), int64(3), object(8)
memory usage: 1.1+ MB

In [5]:
data_mofa_acp.head() #Inspecting dataframe

,region,district,date,Market,source,_geolocation,commodity,Price,market_day,Year,month,week,Type
0,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,NaN,white maize,8.660000,2025-07-16,2025,7,3,retail
1,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,NaN,Maize Yellow,9.485000,2025-07-16,2025,7,3,retail
2,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,NaN,Millet,19.863333,2025-07-16,2025,7,3,retail
3,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,NaN,Rice Local perfumed,20.643333,2025-07-16,2025,7,3,retail
4,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,NaN,Rice Local non perfumed,15.110000,2025-07-16,2025,7,3,retail

In [6]:
data_mofa_acp = data_mofa_acp.drop(columns=['_geolocation']) # Drop due to missing values

In [7]:
data_mofa_acp.head()

,region,district,date,Market,source,commodity,Price,market_day,Year,month,week,Type
0,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,white maize,8.660000,2025-07-16,2025,7,3,retail
1,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Maize Yellow,9.485000,2025-07-16,2025,7,3,retail
2,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Millet,19.863333,2025-07-16,2025,7,3,retail
3,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Rice Local perfumed,20.643333,2025-07-16,2025,7,3,retail
4,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Rice Local non perfumed,15.110000,2025-07-16,2025,7,3,retail

In [8]:
data_mofa_acp["commodity"].value_counts().head(10) # Checking the commodities with the most instances

commodity
white maize            322
Maize Yellow           318
Millet                 300
Cowpea White           288
Rice Local perfumed    279
Garden Egg             277
Gari                   276
Yam Puna               274
Plantain Apentu        259
Fresh Pepper Bonnet    258
Name: count, dtype: int64

##### Filtered commodities to be considered since most of the interviewees worked with these commodities:
 - Rice
 - Maize
 - Soyabean
 - Groundnut

In [15]:
four_commodity_data = data_mofa_acp[data_mofa_acp["commodity"].str.contains("rice", case=False, na=False) | 
data_mofa_acp["commodity"].str.contains("maize", case=False, na=False) | data_mofa_acp["commodity"].str.contains("soy", case=False, na=False)
 | data_mofa_acp["commodity"].str.contains("groundnut", case=False, na=False) ]

four_commodity_data.head()

,region,district,date,Market,source,commodity,Price,market_day,Year,month,week,Type
0,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,white maize,8.660000,2025-07-16,2025,7,3,retail
1,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Maize Yellow,9.485000,2025-07-16,2025,7,3,retail
3,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Rice Local perfumed,20.643333,2025-07-16,2025,7,3,retail
4,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Rice Local non perfumed,15.110000,2025-07-16,2025,7,3,retail
5,Central,Mfantsiman Municipal,16-07-2025,Mankessim,retail,Rice Imported perfumed,20.283333,2025-07-16,2025,7,3,retail

In [16]:
four_commodity_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2153 entries, 0 to 10777
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2153 non-null   object
 1   district    2153 non-null   object
 2   date        2153 non-null   object
 3   Market      2073 non-null   object
 4   source      2153 non-null   object
 5   commodity   2153 non-null   object
 6   Price       2153 non-null   float64
 7   market_day  2153 non-null   object
 8   Year        2153 non-null   int64
 9   month       2153 non-null   int64
 10  week        2153 non-null   int64
 11  Type        2153 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 218.7+ KB

In [17]:
four_commodity_data['commodity'].value_counts()

commodity
white maize                   322
Maize Yellow                  318
Rice Local perfumed           279
Rice Imported perfumed        256
Groundnut Red                 235
Soya Bean                     223
Rice Local non perfumed       200
Rice Imported non perfumed    191
Unshelled Groundnut           102
Groundnut Oil                  27
Name: count, dtype: int64

In [20]:
four_commodity_data = four_commodity_data[~four_commodity_data["commodity"].str.contains("Rice Imported non perfumed", case=False, na=False)]

# four_commodity_data["commodity"].str.contains("Rice Imported perfumed", case=False, na=False)| 
# four_commodity_data["commodity"].str.contains("Groundnut Oil", case=False, na=False)| 
# four_commodity_data["commodity"].str.contains("Rice Imported non perfumed", case=False, na=False)]

In [22]:
four_commodity_data['commodity'].value_counts()

commodity
white maize                322
Maize Yellow               318
Rice Local perfumed        279
Groundnut Red              235
Soya Bean                  223
Rice Local non perfumed    200
Unshelled Groundnut        102
Name: count, dtype: int64

In [23]:
four_commodity_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1679 entries, 0 to 10777
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      1679 non-null   object
 1   district    1679 non-null   object
 2   date        1679 non-null   object
 3   Market      1617 non-null   object
 4   source      1679 non-null   object
 5   commodity   1679 non-null   object
 6   Price       1679 non-null   float64
 7   market_day  1679 non-null   object
 8   Year        1679 non-null   int64
 9   month       1679 non-null   int64
 10  week        1679 non-null   int64
 11  Type        1679 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 170.5+ KB

In [24]:
four_commodity_data.to_csv('four_commodity_data.csv',index=False) # Saving the dataset

### Data from AHIES

In [2]:
micro_data = pd.read_csv(r"C:\Users\rauda\Downloads\AHIES2022Q1_2023Q3_SEC01234_202402.csv",encoding="latin1")
micro_data.info()

C:\Users\rauda\AppData\Local\Temp\ipykernel_15096\157786482.py:1: DtypeWarning: Columns (11,13,30,35,42,44,47,76,77,78,81,83,86,87,88,89,90,91,92,93,94,95,96,97,99,119,121,125,142,147,149,185,237,239,246,259,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,279,280,282,283,285,288,289,292,293,304,305,306,307,308,310,311,313,314,315,316,317,318,319,320,321,325,326,327,328,336,337,338,339,340,343,344,348,353,358,359,360,361,362,363,365,366,367,371,373,375,377,383,388,403,405,406,407,408,412,413,429,435,451,466,468,469,470,471,472,473,474,475,481,487,488,489,495,509,522,523,525,526,527,528,529,530,531,532,539,540,541,554,555,559,605) have mixed types. Specify dtype option on import or set low_memory=False.
  micro_data = pd.read_csv(r"C:\Users\rauda\Downloads\AHIES2022Q1_2023Q3_SEC01234_202402.csv",encoding="latin1")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356437 entries, 0 to 356436
Columns: 607 entries, hhid to urbrur
dtypes: float64(251), int64(5), object(351)
memory usage: 1.6+ GB

In [3]:
micro_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356437 entries, 0 to 356436
Columns: 607 entries, hhid to urbrur
dtypes: float64(251), int64(5), object(351)
memory usage: 1.6+ GB

In [4]:
micro_data.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1,s1aq2,s1aq4y,s1aq4m,s1aq5,...,region,BMI,pop_weight,hh_weight,worked,wagework,nowork,econact,availreason,urbrur
0,500109,2023Q1,1,9,2,Female,Spouse (Wife/Husband/Living together),43,NaN,Married (Customary/Traditional),...,WESTERN,NaN,923.53058,1126.7158,1.0,NaN,NaN,Employed,NaN,Urbanb
1,300109,2022Q3,1,9,3,Male,Child (Son/Daughter),21,NaN,Never married,...,WESTERN,20.672762,863.96033,1016.0422,NaN,NaN,1.0,Not active,NaN,Urbanb
2,600114,2023Q2,1,14,1,Male,Head,39,NaN,Married (Customary/Traditional),...,WESTERN,NaN,933.66388,1113.8646,1.0,1.0,NaN,Employed,NaN,Urbanb
3,600102,2023Q2,1,2,4,Male,Child (Son/Daughter),3,0.0,NaN,...,WESTERN,NaN,933.66388,1113.8646,NaN,NaN,NaN,NaN,NaN,Urbanb
4,300114,2022Q3,1,14,3,Female,Child (Son/Daughter),3,1.0,NaN,...,WESTERN,NaN,863.96033,1016.0422,NaN,NaN,NaN,NaN,NaN,Urbanb

##### Number of columns found from dataset

In [6]:
len(mi_data_columns)

607

In [5]:
mi_data_columns = list(micro_data.columns)

In [41]:
index = mi_data_columns.index("profession") # Checking to see if there is a column named profession

In [50]:
micro_data.iloc[:, 260:280].head(10)

,s4aq45,s4aq46,s4aq46a,s4aq47,s4aq48,s4aq49,s4aq50,s4aq51,s4aq52,s4aq52b,s4aq52c,s4aq52d,s4aq52e,s4aq52o,s4aq52a,s4aq53,s4aq54,s4aq54a,s4aq55a,s4aq55b
0,Permanent: Full time,Non-agric self-employed without employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Permanent: Full time,Paid employee,NaN,"Yes, written",No,Yes,"Yes, paid sick leave.",Yes,BC,Yes,Yes,NaN,NaN,NaN,NaN,No,Time basis,NaN,2360.0,Month
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Temporary: Part-time,Casual worker,NaN,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Time basis,NaN,20.0,Day
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Permanent: Full time,Paid employee,NaN,"Yes, written",No,Yes,"Yes, paid sick leave.",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Time basis,NaN,250.0,Month

In [44]:
micro_data['s4aq28'].value_counts()

s4aq28
No                          177604
Yes, Employment Work        130285
Yes, Non-Employment Work      3657
Name: count, dtype: int64

In [51]:

micro_data['s4aq55b'].value_counts()

s4aq55b
Month        18274
Day           5914
Week          1650
2 Weeks        357
Year           211
Quarter        141
Hour            72
Half year       29
Name: count, dtype: int64

In [ ]:
"""'s2aq1' [Education as whether peson has attended school ]
    's2aq3' - highest level of education
    's4aq40a' - occupation
    's4aq42' - occupation type (registration)
    's4aq44' - occupation place
    's1aq4y'- age
    's1aq9a' - tribe
    's1bq5b' # living place
    's1bq5a' - region of stay
    's1aq5' - marital status

#micro_data['s1bq2b'].value_counts() #- municipality
    
"""

In [57]:
micro_data.iloc[:, :30].head(10)

,hhid,quarter,cluster,HholdID,personid,s1aq1,s1aq2,s1aq4y,s1aq4m,s1aq5,...,s1bq1,s1bq2a,s1bq2o,s1bq2b,s1bq3,s1bq4,s1bq5a,s1bq5b,s1bq6,s1bq7
0,500109,2023Q1,1,9,2,Female,Spouse (Wife/Husband/Living together),43,NaN,Married (Customary/Traditional),...,No,Volta,NaN,ANLOGA (ANLOGA),NaN,19.0,Volta,ANLOGA (ANLOGA),23.0,Settlement (long term/ permanent stay
1,300109,2022Q3,1,9,3,Male,Child (Son/Daughter),21,NaN,Never married,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
2,600114,2023Q2,1,14,1,Male,Head,39,NaN,Married (Customary/Traditional),...,No,Volta,NaN,KPANDO MUNICIPAL (KPANDO),NaN,10.0,Greater Accra,ASHAIMAN MUNICIPAL (ASHAIMAN),27.0,Employment
3,600102,2023Q2,1,2,4,Male,Child (Son/Daughter),3,0.0,NaN,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
4,300114,2022Q3,1,14,3,Female,Child (Son/Daughter),3,1.0,NaN,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
5,200109,2022Q2,1,9,3,Male,Child (Son/Daughter),21,NaN,Never married,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
6,600114,2023Q2,1,14,3,Female,Child (Son/Daughter),3,11.0,NaN,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
7,500114,2023Q1,1,14,3,Female,Child (Son/Daughter),3,7.0,NaN,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
8,700114,2023Q3,1,14,3,Female,Child (Son/Daughter),4,1.0,NaN,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
9,100102,2022Q1,1,2,1,Male,Head,31,NaN,Married (Customary/Traditional),...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN

In [40]:
#micro_data['s1aq9a'].value_counts() - tribe
#micro_data['s1bq2b'].value_counts() #- municipality
#micro_data['s1bq5a'].value_counts() #

In [ ]:
# 'hhid'	'quarter'	'cluster'	'HholdID'	'personid'	's1aq1'- gender	's1aq2'- role in the household.

# 's2aq1' [Education as whether peson has attended school ]
#     's2aq3' - highest level of education
#     's4aq40a' - occupation
#     's4aq42' - occupation type (registration)
#     's4aq44' - occupation place
#     's1aq4y'- age
#     's1aq9a' - tribe
#     's1bq5b' # living place
#     's1bq5a' - region of stay
#     's1aq5' - marital status

In [7]:
narrow_microdata = micro_data[['hhid','quarter','cluster','HholdID','personid','s1aq1','s1aq2','s2aq3',
    's4aq40a','s4aq42','s4aq44','s1aq4y', 's1aq9a','s1bq5b','s1bq5a','s1aq5']]
narrow_microdata.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1,s1aq2,s2aq3,s4aq40a,s4aq42,s4aq44,s1aq4y,s1aq9a,s1bq5b,s1bq5a,s1aq5
0,500109,2023Q1,1,9,2,Female,Spouse (Wife/Husband/Living together),0,FISH SMOKER,Private Informal,Home,43,Ewe,ANLOGA (ANLOGA),Volta,Married (Customary/Traditional)
1,300109,2022Q3,1,9,3,Male,Child (Son/Daughter),SSS/SHS,NaN,Private Informal,NaN,21,Ewe,NaN,NaN,Never married
2,600114,2023Q2,1,14,1,Male,Head,SSS/SHS,POLICE DRIVER,Public (Government),Office,39,Ewe,ASHAIMAN MUNICIPAL (ASHAIMAN),Greater Accra,Married (Customary/Traditional)
3,600102,2023Q2,1,2,4,Male,Child (Son/Daughter),Nursery,NaN,NaN,NaN,3,Akan,NaN,NaN,NaN
4,300114,2022Q3,1,14,3,Female,Child (Son/Daughter),0,NaN,NaN,NaN,3,Ewe,NaN,NaN,NaN

#### The columns that were deciphered.

- 's1aq1'- gender	
- 's1aq2'- role in the household.
- 's2aq1' - Education as whether peson has attended school 
- 's2aq3' - highest level of education
- 's4aq40a' - occupation
- 's4aq42' - occupation type (registration)
- 's4aq44' - occupation place
- 's1aq4y'- age
- 's1aq9a' - tribe
- 's1bq5a' - region of stay
- 's1aq5' - marital status

In [8]:
narrow_microdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356437 entries, 0 to 356436
Data columns (total 16 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   hhid      356437 non-null  int64
 1   quarter   356437 non-null  object
 2   cluster   356437 non-null  int64
 3   HholdID   356437 non-null  int64
 4   personid  356437 non-null  int64
 5   s1aq1     356437 non-null  object
 6   s1aq2     356437 non-null  object
 7   s2aq3     330887 non-null  object
 8   s4aq40a   158178 non-null  object
 9   s4aq42    158113 non-null  object
 10  s4aq44    156551 non-null  object
 11  s1aq4y    356437 non-null  int64
 12  s1aq9a    353634 non-null  object
 13  s1bq5b    108080 non-null  object
 14  s1bq5a    108080 non-null  object
 15  s1aq5     242003 non-null  object
dtypes: int64(5), object(11)
memory usage: 43.5+ MB

##### Renaming deciphered columns to reflect actual context meaning.
- Also included original codes to for easy tracking

In [9]:
narrow_microdata = narrow_microdata.rename(columns={'s1aq1': 's1aq1_gender','s1aq2': 's1aq2_ role_in_household','s2aq1': 's2aq1_education',
                               's2aq3': 's2aq3_highest_level_of_education', 's4aq40a':'s4aq40a_occupation','s4aq42': 's4aq42_occupation_type_registration',
                                's4aq44':'s4aq44_occupation_place','s1aq4y':'s1aq4y_age','s1aq9a':'s1aq9a_tribe','s1bq5a':'s1bq5a_region of stay',
                                's1aq5':'s1aq5_marital_status'})

narrow_microdata.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1_gender,s1aq2_ role_in_household,s2aq3_highest_level_of_education,s4aq40a_occupation,s4aq42_occupation_type_registration,s4aq44_occupation_place,s1aq4y_age,s1aq9a_tribe,s1bq5b,s1bq5a_region of stay,s1aq5_marital_status
0,500109,2023Q1,1,9,2,Female,Spouse (Wife/Husband/Living together),0,FISH SMOKER,Private Informal,Home,43,Ewe,ANLOGA (ANLOGA),Volta,Married (Customary/Traditional)
1,300109,2022Q3,1,9,3,Male,Child (Son/Daughter),SSS/SHS,NaN,Private Informal,NaN,21,Ewe,NaN,NaN,Never married
2,600114,2023Q2,1,14,1,Male,Head,SSS/SHS,POLICE DRIVER,Public (Government),Office,39,Ewe,ASHAIMAN MUNICIPAL (ASHAIMAN),Greater Accra,Married (Customary/Traditional)
3,600102,2023Q2,1,2,4,Male,Child (Son/Daughter),Nursery,NaN,NaN,NaN,3,Akan,NaN,NaN,NaN
4,300114,2022Q3,1,14,3,Female,Child (Son/Daughter),0,NaN,NaN,NaN,3,Ewe,NaN,NaN,NaN

##### Limiting the occupation to only farmer

In [10]:
farmer_data =narrow_microdata[narrow_microdata["s4aq40a_occupation"].str.contains(" farmer ", case=False, na=False)]
farmer_data.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1_gender,s1aq2_ role_in_household,s2aq3_highest_level_of_education,s4aq40a_occupation,s4aq42_occupation_type_registration,s4aq44_occupation_place,s1aq4y_age,s1aq9a_tribe,s1bq5b,s1bq5a_region of stay,s1aq5_marital_status
8011,301801,2022Q3,18,1,3,Male,Child (Son/Daughter),JSS/JHS,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,18,Akan,NaN,NaN,Never married
8023,701817,2023Q3,18,17,1,Male,Head,Primary,COCOA FARMER LABOURER,Private Informal,Other land / farm.,52,Mole-Dagbani,BEREKUM EAST MUNICIPAL (BEREKUM),Bono,Married (Islamic)
8069,301816,2022Q3,18,16,3,Male,Child (Son/Daughter),JSS/JHS,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,27,Akan,NaN,NaN,Never married
8329,601817,2023Q2,18,17,4,Female,Child (Son/Daughter),0,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,16,Mole-Dagbani,BEREKUM EAST MUNICIPAL (BEREKUM),Bono,Never married
8335,301801,2022Q3,18,1,5,Female,Child (Son/Daughter),Primary,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,11,Akan,NaN,NaN,NaN

In [11]:
farmer_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2347 entries, 8011 to 356431
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   hhid                                 2347 non-null   int64
 1   quarter                              2347 non-null   object
 2   cluster                              2347 non-null   int64
 3   HholdID                              2347 non-null   int64
 4   personid                             2347 non-null   int64
 5   s1aq1_gender                         2347 non-null   object
 6   s1aq2_ role_in_household             2347 non-null   object
 7   s2aq3_highest_level_of_education     2340 non-null   object
 8   s4aq40a_occupation                   2347 non-null   object
 9   s4aq42_occupation_type_registration  2278 non-null   object
 10  s4aq44_occupation_place              2319 non-null   object
 11  s1aq4y_age                           2347 non-null   int64
 12  s1aq9a_tribe                         2330 non-null   object
 13  s1bq5b                               692 non-null    object
 14  s1bq5a_region of stay                692 non-null    object
 15  s1aq5_marital_status                 2281 non-null   object
dtypes: int64(5), object(11)
memory usage: 311.7+ KB

##### Limiting ages to 18 and above

In [12]:
farmer_data_above =farmer_data[farmer_data['s1aq4y_age']>17]
farmer_data_above.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1_gender,s1aq2_ role_in_household,s2aq3_highest_level_of_education,s4aq40a_occupation,s4aq42_occupation_type_registration,s4aq44_occupation_place,s1aq4y_age,s1aq9a_tribe,s1bq5b,s1bq5a_region of stay,s1aq5_marital_status
8011,301801,2022Q3,18,1,3,Male,Child (Son/Daughter),JSS/JHS,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,18,Akan,NaN,NaN,Never married
8023,701817,2023Q3,18,17,1,Male,Head,Primary,COCOA FARMER LABOURER,Private Informal,Other land / farm.,52,Mole-Dagbani,BEREKUM EAST MUNICIPAL (BEREKUM),Bono,Married (Islamic)
8069,301816,2022Q3,18,16,3,Male,Child (Son/Daughter),JSS/JHS,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,27,Akan,NaN,NaN,Never married
8550,601816,2023Q2,18,16,5,Male,Child (Son/Daughter),SSS/SHS,CASSAVA FARMER (FAMILY CONTRIBUTING WORKER ),Private Informal,Own land / farm,18,Akan,NaN,NaN,Never married
8751,501903,2023Q1,19,3,3,Female,Child (Son/Daughter),JSS/JHS,COCOA FARMER (FAMILY CONTRIBUTING WORKER),Private Informal,Own land / farm,18,Ewe,NaN,NaN,Never married

In [ ]:
# Checking for unique value counts of occupation
farmer_data_above['s4aq40a_occupation'].value_counts()

In [51]:
crop_type = list(farmer_data_above['s4aq40a_occupation'].unique())
crop_type #Checking for irrelevant roles

##### Removing words that are not related to crop farming and other occupations support farmer
Words removed : labourer, livestock farmer, poultry farmer, fish farmer, worker

In [22]:

farmer_data_above = farmer_data_above[~farmer_data_above["s4aq40a_occupation"].str.contains("worker", case=False, na=False)] # repeated this step until all the words mentioned above were removed
crop_type = list(farmer_data_above['s4aq40a_occupation'].unique())

In [37]:
farmer_data_above = farmer_data_above.drop(['s1bq5b'], axis=1)

In [38]:
farmer_data_above.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1926 entries, 13423 to 356431
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   hhid                                 1926 non-null   int64
 1   quarter                              1926 non-null   object
 2   cluster                              1926 non-null   int64
 3   HholdID                              1926 non-null   int64
 4   personid                             1926 non-null   int64
 5   s1aq1_gender                         1926 non-null   object
 6   s1aq2_ role_in_household             1926 non-null   object
 7   s2aq3_highest_level_of_education     1923 non-null   object
 8   s4aq40a_occupation                   1926 non-null   object
 9   s4aq42_occupation_type_registration  1877 non-null   object
 10  s4aq44_occupation_place              1918 non-null   object
 11  s1aq4y_age                           1926 non-null   int64
 12  s1aq9a_tribe                         1911 non-null   object
 13  s1bq5a_region of stay                627 non-null    object
 14  s1aq5_marital_status                 1926 non-null   object
dtypes: int64(5), object(10)
memory usage: 240.8+ KB

In [39]:
farmer_data_above.head()

,hhid,quarter,cluster,HholdID,personid,s1aq1_gender,s1aq2_ role_in_household,s2aq3_highest_level_of_education,s4aq40a_occupation,s4aq42_occupation_type_registration,s4aq44_occupation_place,s1aq4y_age,s1aq9a_tribe,s1bq5a_region of stay,s1aq5_marital_status
13423,102813,2022Q1,28,13,1,Female,Head,Primary,MIXED CROP FARMER WITH CASSAVA AS MAJOR,Private Informal,Own land / farm,57,Akan,NaN,Married (Customary/Traditional)
16026,203211,2022Q2,32,11,1,Male,Head,Middle,INTER LIN3 FARMER AT BOPP,Private Formal,Factory,49,Akan,Central.,Married (Islamic)
21703,604106,2023Q2,41,6,1,Male,Head,JSS/JHS,A COCOA FARMER FARMER,Private Informal,Own land / farm,44,Gurma,Northern.,Married (Civil/Ordinance)
35292,406907,2022Q4,69,7,2,Female,Spouse (Wife/Husband/Living together),JSS/JHS,A CASSAVA FARMER AND MANUFACTURING OF GARI,Private Informal,Other land / farm.,33,Akan,NaN,Married (Customary/Traditional)
40324,107919,2022Q1,79,19,1,Male,Head,Middle,COCOA FARMER AT OKITEW,Private Informal,Own land / farm,61,Akan,Greater Accra,Married (Customary/Traditional)

In [27]:
farmer_data_above.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1926 entries, 13423 to 356431
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   hhid                                 1926 non-null   int64
 1   quarter                              1926 non-null   object
 2   cluster                              1926 non-null   int64
 3   HholdID                              1926 non-null   int64
 4   personid                             1926 non-null   int64
 5   s1aq1_gender                         1926 non-null   object
 6   s1aq2_ role_in_household             1926 non-null   object
 7   s2aq3_highest_level_of_education     1923 non-null   object
 8   s4aq40a_occupation                   1926 non-null   object
 9   s4aq42_occupation_type_registration  1877 non-null   object
 10  s4aq44_occupation_place              1918 non-null   object
 11  s1aq4y_age                           1926 non-null   int64
 12  s1aq9a_tribe                         1911 non-null   object
 13  s1bq5b                               627 non-null    object
 14  s1bq5a_region of stay                627 non-null    object
 15  s1aq5_marital_status                 1926 non-null   object
dtypes: int64(5), object(11)
memory usage: 255.8+ KB

##### Saving sample dataset

In [52]:
farmer_data_above.to_csv("farmer_data_ahies.csv",index=False)